chat:
  enabled: true
  local:
    disable: false
    radius: 100.0
    format: "<gray>[L] %displayname%: <white>%message%"
    show-no-one-message: true
    show-message-anyway: true
  global:
    prefix: "!"
    format: "<aqua>[G] <gray>%displayname%: <white>%message%"
  message-colors:
    enabled: true
    mercury: "<gold>"
    moon: "<gray>"
    mars: "<red>"
    admin: "<red>"
    default: "<white>"

admin-chat:
  enabled: true
  prefix-symbol: "@"
  format: "<red>[AdminChat] <gray>%displayname%: <white>%message%"

mod-chat:
  enabled: true
  prefix-symbol: "?"
  format: "<blue>[ModChat] <gray>%displayname%: <white>%message%"

donor-chat:
  enabled: true
  prefix-symbol: "$"
  format: "<gold>[DonorChat] <gray>%displayname%: <white>%message%"

join-quit:
  enabled: true
  disable-join: false
  disable-quit: false
  join-format: "<green>%player% <gray>зашел на сервер"
  quit-format: "<red>%player% <gray>вышел с сервера"

death:
  enabled: true
  disable-public: false
  disable-private: false
  public-format: "<gray>%player% died"
  private-format: "<gray>Вы умерли от <white>%killer%\n<gray>Координаты: <white>%x%<gray>, <white>%y%<gray>, <white>%z% <gray>(<white>%world%<gray>)"

advancement:
  enabled: true
  disable: false
  format: "<gold>%player% <gray>получил достижение: <white>%advancement%"

auto-messages:
  enabled: true
  interval-seconds: 300
  messages:
    - "<gradient:#00FFFF:#0088FF>https://t.me/vibestudiomc</gradient>"

commands:
  cooldown-milliseconds: 1000
